package org.tzi.use.plugins.bdi.trace;

public enum TraceNodeKind {
    SOURCE,
    BDI_ELEMENT,
    MAPPING,
    UML_ELEMENT,
    OCL_CONSTRAINT,
    ENVIRONMENT_ARTIFACT,
    ARTIFACT_OPERATION,
    OBSERVABLE_PROPERTY,
    ORGANIZATION,
    ORGANIZATION_ROLE,
    ORGANIZATION_MISSION,
    ORGANIZATION_CARDINALITY,
    GAP,
    ISSUE
}
