package org.tzi.use.plugins.bdi.report;

import java.nio.file.Path;
import java.time.Instant;

public final class ReportMain {
    public static void main(String[] args) {
        try {
            Path out = Path.of(System.getProperty("user.dir"), "docs", "bdi-report.json");
            ReportData data = new ReportData(
                    "USE-BDI-Project",
                    "0.1.0",
                    "USE-7.1.1",
                    Instant.now(),
                    /*issuesCount*/ 0,
                    /*mappingsCount*/ 0,
                    "auto-generated by ReportMain"
            );

            ReportExporter.exportJson(data, out);
            System.out.println("Wrote report to: " + out.toAbsolutePath());
            System.exit(0);
        } catch (Exception e) {
            e.printStackTrace(System.err);
            System.exit(2);
        }
    }
}
