package org.tzi.use.plugins.bdi.report;

import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Instant;
import java.util.List;
import java.util.Optional;

import org.tzi.use.plugins.bdi.persistence.SuppressionRepository;
import org.tzi.use.plugins.bdi.validation.Suppression;

public final class ReportMain {
    public static void main(String[] args) {
        try {
            Path projectRoot = Path.of(System.getProperty("user.dir"));
            Path out = projectRoot.resolve(Path.of("docs", "bdi-report.json"));
            Path suppressionFile = projectRoot.resolve(Path.of(
                    "use-bdi-plugin", ".bdi-plugin", "suppressions.json"));
            List<Suppression> suppressions = Files.exists(suppressionFile)
                    ? new SuppressionRepository().load(suppressionFile)
                    : List.of();
            ReportData data = new ReportData(
                    "USE-BDI-Project",
                    "0.1.0",
                    "USE-7.1.1",
                    Instant.now(),
                    /*issuesCount*/ 0,
                    /*mappingsCount*/ 0,
                    "auto-generated by ReportMain",
                    Optional.empty(),
                    Optional.empty(),
                    List.of(),
                    suppressions
            );

            ReportExporter.exportJson(data, out);
            System.out.println("Wrote report to: " + out.toAbsolutePath());

            Path outHtml = projectRoot.resolve(Path.of("docs", "bdi-report.html"));
            HtmlReportExporter.exportHtml(data, outHtml);
            System.out.println("Wrote HTML report to: " + outHtml.toAbsolutePath());
            System.exit(0);
        } catch (Exception e) {
            e.printStackTrace(System.err);
            System.exit(2);
        }
    }
}
