[config1]

Integer_min = -10
Integer_max = 10

String_max = 10


# --------------------------------------------------------------------- Snapshot
Snapshot_min = 3
Snapshot_max = 3

# Filmstrip (pred:Snapshot, succ:Snapshot, operationCall:OperationCall)  - - - -
Filmstrip_min = 2
Filmstrip_max = 2

# ---------------------------------------------------------------- OperationCall

# ----------------------------------------------------------------- SnapshotItem

# SnapElement (snapshotItem:SnapshotItem, snapshot:Snapshot) - - - - - - - - - -
SnapElement_min = 3
SnapElement_max = 3

# -------------------------------------------------------------- step1_ClassAOpC
step1_ClassAOpC_min = 1
step1_ClassAOpC_max = 1

step1_ClassAOpC_a_min = -1
step1_ClassAOpC_a_max = -1

# -------------------------------------------------------------- step2_ClassAOpC
step2_ClassAOpC_min = 1
step2_ClassAOpC_max = 1

step2_ClassAOpC_b_min = -1
step2_ClassAOpC_b_max = -1

# -------------------------------------------------------------------- ClassAOpC

ClassAOpC_aSelf_min = -1
ClassAOpC_aSelf_max = -1

# ----------------------------------------------------------------------- ClassA
ClassA_min = 3
ClassA_max = 3

ClassA_changedAttr_min = -1
ClassA_changedAttr_max = -1
ClassA_curStep_min = -1
ClassA_curStep_max = -1
ClassA_unchanedAttr_min = -1
ClassA_unchanedAttr_max = -1

# PredSuccClassA (pred:ClassA, succ:ClassA)  - - - - - - - - - - - - - - - - - -
PredSuccClassA_min = 2
PredSuccClassA_max = 2

# SnapshotClassA (classA:ClassA, snapshotClassA:Snapshot)  - - - - - - - - - - -
SnapshotClassA_min = 3
SnapshotClassA_max = 3
# ------------------------------------------------------------------------------
aggregationcyclefreeness = on
forbiddensharing = on

