[step1_step2]

Integer_min = -10
Integer_max = 10

String_max = 10

------------Usecase Class
ClassA_min = 1
ClassA_max = 1

ClassA_curStep = Set{'','step1', 'step2'}

--SnapshotClassA_min = 3
--SnapshotClassA_max = 3

--PredSuccClassA_min = 2
--PredSuccClassA_max = 2

------------Model class, Snapshot association, PredSucc association
--DomainClass_min = 1
--DomainClass_max = 1

--SnapshotDomainClass_min = 1
--SnapshotDomainClass_max = 1

--PredSucc_DomainClass_min = 2
--PredSucc_DomainClass_max = 2

--------------Snapshot & Filmstrip
--Snapshot_min = 1
--Snapshot_max = 1

--Filmstrip_min = 2
--Filmstrip_max = 2

-------------Operation Class OpC
--actStep_step01a_BuyTicketOpC_min = 0
--actStep_step01a_BuyTicketOpC_max = 0

-------------Model Association
--TakeTicket_min = 0
--TakeTicket_max = -1
